name: nexus_mobile_app
description: Companion app for Nexus OMS

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^3.3.3
  flutter_cache_manager: ^1.4.1
  provider: ^4.1.3
  intl: ^0.16.1
  url_launcher: ^5.5.0
  connectivity: ^0.4.8+6
  google_fonts: ^1.1.0
  outline_material_icons: ^0.1.1
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0
  flutter_widget_from_html_core: ^0.4.1
  http: ^0.12.2
  uni_links: ^0.4.0
  shimmer: ^1.1.1
  material_design_icons_flutter: 4.0.5345
  firebase_ml_vision: ^0.9.6+2
  camera: ^0.5.8+5
  flushbar: ^1.10.4
  flutter_downloader: ^1.5.0
  path_provider: ^1.6.14
  cached_network_image: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_flat.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
  assets:
      - assets/icon/icon_transparent.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true